spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/home
    username: postgres
    password: 1309
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true
server:
  hostname: localhost
  port: ${PORT:8080}
mail:
  server:
    host: smtp.gmail.com
    port: 587
    username: kenesvip@gmail.com
    password: Kojikov89$$

